# Generated by Django 5.1.1 on 2024-10-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('calificacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_alfanumerico', models.CharField(max_length=10, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('frecuencia', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_parada', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('num_unidad', models.IntegerField(unique=True)),
                ('fecha_compra', models.DateField()),
                ('estado_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.estadobus')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('tipo_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.tipoparada')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio_programado', models.TimeField()),
                ('horario_fin_programado', models.TimeField()),
                ('fecha_viaje', models.DateField()),
                ('marca_inicio_viaje_real', models.DateTimeField(blank=True, null=True)),
                ('marca_fin_viaje_real', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.bus')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.chofer')),
                ('estado_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.estadoviaje')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='AtractivoXParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.atractivo')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.parada')),
            ],
            options={
                'unique_together': {('parada', 'atractivo')},
            },
        ),
        migrations.CreateModel(
            name='OrdenParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion_paradas', models.IntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.parada')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbus.recorrido')),
            ],
            options={
                'unique_together': {('parada', 'recorrido')},
            },
        ),
    ]
