# Generated by Django 5.1.1 on 2024-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='codigo_alfanumerico',
            field=models.CharField(max_length=10),
        ),
    ]
