# Generated by Django 5.1.1 on 2024-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbus', '0002_alter_recorrido_codigo_alfanumerico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='imagen',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
