# Generated by Django 5.1.1 on 2024-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbus', '0003_alter_parada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
