# Generated by Django 5.1.1 on 2024-10-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbus', '0005_alter_parada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
